### GET request
GET http://localhost:3000/availability/12345

### Send POST request with json body
POST http://localhost:3000/availability
Content-Type: application/json

{
  "Name": "John",
  "Pass": "content"
}

### Send POST request with form encoded body and random values
POST http://localhost:3000/availability
Content-Type: application/x-www-form-urlencoded

Name = {{$uuid}} &Pass = {{$randomInt}}

### Send POST request with body as parameters
POST https://httpbin.org/post
Content-Type: application/x-www-form-urlencoded

id=999&value=content

### Send request with dynamic variables in request's body
POST https://httpbin.org/post
Content-Type: application/json

{
  "id": {{$uuid}},
  "price": {{$randomInt}},
  "ts": {{$timestamp}},
  "value": "content"
}

###